### ISSUE TITLE
Liked Songs

### ISSUE THREAD

**Issue by pascalinger** [SoloUnity/alfred-Spotify-Commands#2]
Hi there,

Great work on this script!

- Is there a way to use !q to play the liked songs on shuffle?
- Can I like a song thats playing currently using a hotkey?

**Comment by SoloUnity** [comment]
These both seem doable, I'll get something out on the weekend if I have time.

**Comment by SoloUnity** [comment]
The easiest way play liked songs is just to make a playlist with them as that isn't exposed in the applescript api, which liking isn't either. Sorry!
