### ISSUE TITLE
Loop current track in a playlist

### ISSUE THREAD

**Issue by IHToby** [SoloUnity/alfred-Spotify-Commands#4]
Thanks for your effort! 
Btw I would like to ask is there any method to only loop the current track in a playlist? I can't find the applescript from the internet.

**Comment by SoloUnity** [comment]
You might be able to get the song duration, and have the script play the same song again after waiting for said duration. I have not looked into it yet though. Otherwise there's no way to do it with applescript.

**Comment by IHToby** [comment]
Good idea! Maybe we can give it a try.
